# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Commons
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  # -   id: check-added-large-files
- repo: local
  hooks:
    - id: nixpkgs-fmt
      name: nixpkgs-fmt
      description: Format nix code with nixpkgs-fmt.
      language: system
      entry: nixpkgs-fmt
      files: \.nix$
      stages: [commit]
    # - id: "docupdate"
    #   name: "docupdate"
    #   description: Update documentation.
    #   language: system
    #   entry: just doc-update
    #   stages: [commit]
    #   files: ^README\.md$
    # - id: "markdownlint"
    #   name: "markdownlint"
    #   description: Format markdown code with markdownlint.
    #   language: system
    #   entry: markdownlint
    #   stages: [commit]
    #   files: \.md$
    - id: "deno-fmt"
      name: "deno-fmt"
      description: Format deno code with deno fmt.
      language: system
      entry: deno fmt
      stages: [commit]
      files: \.ts$
    - id: "deno-lint"
      name: "deno-lint"
      description: Lint deno code with deno lint.
      language: system
      entry: deno lint
      stages: [commit]
      files: \.ts$
