version: '3.8'
services:
  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    restart: unless-stopped
    user: '472'
    ports:
      - '3000:3000'
    volumes:
      - $PWD/grafana:/var/lib/grafana
      - $PWD/db:/db
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource 3.5.0
