#!/usr/bin/python
import os
import sys
import csv

import argparse
import pandas as pd

import sqlite3

from tabulate import tabulate

# For pipe exception error
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)


def convert2gnuplot(df, args):
    result = ""
    # Add comments
    result += "# Generated by https://github.com/badele/world-datas-analysis\n"
    result += f"# Query: {args['query']}\n"
    if args['comment']:
        for comment in args['comment']:
            result += f"# {comment}\n"
    result += "\n"

    # Add datas
    group_by_columns = args['block_by'].split(',')
    g = df.groupby(group_by_columns)
    lastcolumn = list(g.groups)[-1]

    for groupname, items in g:
        # Quoting string content contains a space
        for column in items.columns:
            if items[column].dtype == object:
                mask = items[column].astype(str).str.contains(" ")
                items[column][mask] = '"' + items[column][mask] + '"'

        text = tabulate(
            items,
            headers=items.columns,
            floatfmt=".6f",
            showindex="never",
            tablefmt='plain'
        )

        # Show comments
        result += f"# {group_by_columns[0]}={groupname}\n"
        # Write datas
        result += text

        if groupname != lastcolumn:
            result += "\n\n\n"

    return result


# Set pandas options
pd.set_option('mode.chained_assignment', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

# Argument options
ap = argparse.ArgumentParser()
ap.add_argument("--db",  type=str, help="database")
ap.add_argument("--query",  type=str, help="query")
ap.add_argument("--block-by", type=str,
                help="block by column")

# Output
ap.add_argument("--comment", action='append',
                help="Add comment")
ap.add_argument("--output", type=str,
                help="output filename")
args = vars(ap.parse_args())


# Execute query:
conn = sqlite3.connect(args['db'])
with conn:
    df = pd.read_sql_query(args['query'], conn)

# Save
if args['output']:
    # Fill missing value
    df = df.fillna("?")
    # df = df.rename({df.columns[0]: f'# {df.columns[0]}'}, axis=1)

    with open(args['output'], 'w') as f:

        f.write(convert2gnuplot(df, args))
else:
    sys.stdout.write((convert2gnuplot(df, args)))
