{
 "title": "Sirene etablissements",
 "time": { "from": "now-6y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "section",
    "query": "SELECT distinct insee_section_id || ':' || insee_section as __text,insee_section_id as __value from wda_sirene_etablissements"
   },
   {
    "name": "division",
    "query": "SELECT distinct insee_division_id || ':' || insee_division as __text,insee_division_id as __value from wda_sirene_etablissements WHERE insee_section_id IN (${section:sqlstring})"
   },
   {
    "name": "groupe",
    "query": "SELECT distinct insee_groupe_id || ':' || insee_groupe as __text,insee_groupe_id as __value from wda_sirene_etablissements WHERE insee_division_id IN (${division:sqlstring})"
   },
   {
    "name": "classe",
    "query": "SELECT distinct insee_classe_id || ':' || insee_classe as __text,insee_classe_id as __value from wda_sirene_etablissements WHERE insee_groupe_id IN (${groupe:sqlstring})"
   },
   {
    "name": "sousclasse",
    "query": "SELECT distinct insee_sous_classe_id || ':' || insee_sous_classe as __text,insee_sous_classe_id as __value from wda_sirene_etablissements WHERE insee_classe_id IN (${classe:sqlstring})"
   },
   {
    "name": "effectif",
    "query": "SELECT distinct ets_minnbeffectifsetablissement FROM wda_sirene_etablissements where ets_minnbeffectifsetablissement is not null AND insee_sous_classe_id IN (${sousclasse:sqlstring});"
   },
   {
    "name": "departement",
    "query": "SELECT distinct ets_departementetablissement  from wda_sirene_etablissements WHERE  insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring});"
   },
   {
    "name": "ville",
    "query": "SELECT distinct ets_geonames_city FROM wda_sirene_etablissements where  insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring}) AND ets_departementetablissement IN (${departement:sqlstring});"
   }
  ]
 },
 "panels": [
  {
   "title": "Nomenclature",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "https://www.insee.fr/fr/statistiques/fichier/2406147/Nomenclatures_NAF_et_CPF_Reedition_2020.pdf"
   }
  },
  {
   "title": "Section",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT insee_section,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_section_id IN (${section:sqlstring})\nGROUP BY insee_section\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Division",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT insee_division,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_division_id IN (${division:sqlstring})\nGROUP BY insee_division\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Groupe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT insee_groupe,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_groupe_id IN (${groupe:sqlstring})\nGROUP BY insee_groupe\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Classe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT insee_classe,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_classe_id IN (${classe:sqlstring})\nGROUP BY insee_classe\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Sous classe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT insee_sous_classe,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_classe_id IN (${classe:sqlstring})\nGROUP BY insee_sous_classe\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Departement",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ets_departementetablissement,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring}) AND ets_departementetablissement in (${departement:sqlstring})\nGROUP BY ets_departementetablissement\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Villes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ets_geonames_city,count(*) AS nb\nFROM wda_sirene_etablissements\nWHERE insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring}) AND ets_departementetablissement IN (${departement:sqlstring}) AND ets_geonames_city IN (${ville:sqlstring})\nGROUP BY ets_geonames_city\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Result",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT ets_siret,ets_siren,ets_datecreationetablissement,ets_etablissementsiege,ets_minnbeffectifsetablissement,ets_numerovoieetablissement,ets_typevoieetablissement, ets_libellevoieetablissement,ets_codepostaletablissement,ets_departementetablissement,ets_geonames_city,ets_enseigne1etablissement,ets_enseigne2etablissement,ets_enseigne3etablissement,ets_denominationusuelleetablissement,insee_sous_classe\nFROM wda_sirene_etablissements\nWHERE insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring}) AND ets_departementetablissement IN (${departement:sqlstring}) AND ets_geonames_city IN (${ville:sqlstring})\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT ets_siret,ets_siren,ets_datecreationetablissement,ets_etablissementsiege,ens_denominationUniteLegale, ens_denominationUsuelle1UniteLegale, ets_denominationusuelleetablissement, ets_minnbeffectifsetablissement,ets_numerovoieetablissement,ets_typevoieetablissement, ets_libellevoieetablissement,ets_codepostaletablissement,ets_departementetablissement,ets_geonames_city,ets_enseigne1etablissement,ets_enseigne2etablissement,ets_enseigne3etablissement,insee_sous_classe,ets_latitude,ets_longitude\nFROM wda_sirene_etablissements\nWHERE insee_sous_classe_id IN (${sousclasse:sqlstring}) AND ets_minnbeffectifsetablissement IN (${effectif:sqlstring}) AND ets_departementetablissement IN (${departement:sqlstring}) AND ets_geonames_city IN (${ville:sqlstring})\n\n"
    }
   ]
  }
 ]
}