{
 "title": "Vigilo observations",
 "time": { "from": "now-6y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "SELECT DISTINCT geonames_admin1_name FROM wda_vigilo_observations"
   },
   {
    "name": "departement",
    "query": "SELECT DISTINCT geonames_admin2_name FROM wda_vigilo_observations WHERE geonames_admin1_name IN (${region:sqlstring})"
   },
   {
    "name": "arrondissement",
    "query": "SELECT DISTINCT geonames_admin3_name FROM wda_vigilo_observations WHERE geonames_admin1_name IN (${region:sqlstring}) AND geonames_admin2_name IN (${departement:sqlstring}) "
   },
   {
    "name": "ville",
    "query": "SELECT DISTINCT geonames_admin4_name FROM wda_vigilo_observations WHERE geonames_admin1_name IN (${region:sqlstring}) AND geonames_admin2_name IN (${departement:sqlstring})  AND geonames_admin3_name IN (${arrondissement:sqlstring}) "
   },
   {
    "name": "quartier",
    "query": "SELECT DISTINCT geonames_name FROM wda_vigilo_observations WHERE geonames_admin1_name IN (${region:sqlstring}) AND geonames_admin2_name IN (${departement:sqlstring})  AND geonames_admin3_name IN (${arrondissement:sqlstring}) AND geonames_admin4_name IN (${ville:sqlstring}) "
   },
   {
    "name": "category",
    "query": "SELECT DISTINCT cat_name from wda_vigilo_observations"
   }
  ]
 },
 "panels": [
  {
   "title": "Régions",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT geonames_admin1_name,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_admin1_name IN (${region:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY geonames_admin1_name\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Départements",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT geonames_admin2_name,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_admin2_name IN (${departement:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY geonames_admin2_name\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Arrondissement",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT geonames_admin3_name ,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_admin3_name IN (${arrondissement:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY geonames_admin3_name\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Ville",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT geonames_admin4_name,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_admin4_name IN (${ville:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY geonames_admin4_name\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Quartier",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT geonames_name,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY geonames_name\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(obs_ts)*1000 AS ts\nFROM wda_vigilo_observations \nWHERE geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})"
    }
   ]
  },
  {
   "title": "observations",
   "type": "timeseries",
   "description": "Basé sur le filtre des villes",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "-- 24h => 86400\n-- week =>604800\n-- 30 days => 2592000\nSELECT  cast((obs_ts / ($__interval_ms / 1000) ) as bigint) * ($__interval_ms / 1000)*1000 AS ts_in_milliseconds,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY ts_in_milliseconds"
    }
   ]
  },
  {
   "title": "nb observations",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "obs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cat_name as category,count(*) AS nb\nFROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})\nGROUP BY category\nORDER BY nb DESC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 18, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT geonames_admin1_name AS geonames_region, geonames_admin2_name AS departement,geonames_admin3_name AS arrondissement, geonames_admin4_name AS ville, geonames_name as quartier, obs_token,obs_latitude,obs_longitude,obs_address,cat_name AS category,obs_approved\n‣ FROM wda_vigilo_observations \nWHERE obs_ts >= $__from / 1000  and obs_ts < $__to /1000  AND geonames_name IN (${quartier:sqlstring}) AND cat_name IN (${category:sqlstring})\n"
    }
   ]
  }
 ]
}